trigger:
- main
pool:
  vmImage: ubuntu-latest
steps:
- script: |
     python -m venv xpto
     source xpto/bin/activate
     python -m pip install --upgrade pip
     pip install ansible
     ansible-playbook playbook_desafio2.yml
     cat /tmp/teste.txt
     deactivate
  displayName: "Install requirements"
